INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (11, 'RONDÔNIA', 'RO');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (12, 'ACRE', 'AC');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (13, 'AMAZONAS', 'AM');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (14, 'RORAIMA', 'RR');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (15, 'PARÁ', 'PA');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (16, 'AMAPÁ', 'AP');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (17, 'TOCANTINS', 'TO');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (21, 'MARANHÃO', 'MA');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (22, 'PIAUÍ', 'PI');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (23, 'CEARÁ', 'CE');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (24, 'RIO GRANDE DO NORTE', 'RN');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (25, 'PARAÍBA', 'PB');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (26, 'PERNAMBUCO', 'PE');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (27, 'ALAGOAS', 'AL');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (28, 'SERGIPE', 'SE');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (29, 'BAHIA', 'BA');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (31, 'MINAS GERAIS', 'MG');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (32, 'ESPÍRITO SANTO', 'ES');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (33, 'RIO DE JANEIRO', 'RJ');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (35, 'SÃO PAULO', 'SP');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (41, 'PARANÁ', 'PR');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (42, 'SANTA CATARINA', 'SC');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (43, 'RIO GRANDE DO SUL', 'RS');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (50, 'MATO GROSSO DO SUL', 'MS');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (51, 'MATO GROSSO', 'MT');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (52, 'GOIÁS', 'GO');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (53, 'DISTRITO FEDERAL', 'DF');
INSERT INTO SYS_ESTADOS (CD_ESTADO, NM_ESTADO, UF_ESTADO)
                 VALUES (99, 'EXTERIOR', 'EX');

COMMIT WORK;
