INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (1, '¡GUAS BRANCAS', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (3, '¡GUAS LINDAS', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (4, 'ATALAIA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (5, 'AUR¡', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (6, 'CENTRO', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (7, 'CIDADE NOVA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (8, 'COQUEIRO', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (9, 'CURU«AMB¡', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (10, 'DISTRITO INDUSTRIAL', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (11, 'GUANABARA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (12, 'ICUÕ-GUAJAR¡', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (13, 'ICUÕ-LARANJEIRA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (14, 'ILHA JO√O PILATOS', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (15, 'JIB”IA BRANCA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (16, 'LEVIL¬NDIA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (17, 'MAGUARI', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (18, 'MARITUBA', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (19, 'PATO MACHO', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (20, 'QUARENTA HORAS (COQUEIRO)', 161);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (21, 'MARCO', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (22, '¡ÅGUA BOA (OUTEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (23, '¡GUAS LINDAS', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (24, '¡ÅGUAS NEGRAS (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (25, 'AEROPORTO (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (26, 'AGULHA (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (27, 'ARIRAMBA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (28, 'AUR¡', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (29, 'BAÕA DO SOL (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (30, 'BARREIRO', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (31, 'BATISTA CAMPOS', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (32, 'BENGUI', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (33, 'BONFIM (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (34, 'BRASÕLIA (OUTEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (35, 'CABANAGEM', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (36, 'CAMPINA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (37, 'CAMPINA DE ICOARACI (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (38, 'CANUDOS', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (39, 'CARANANDUBA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (40, 'CARUARA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (41, 'CASTANHEIRA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (42, 'CHAP…U VIRADO (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (43, 'CIDADE VELHA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (44, 'CONDOR', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (45, 'COQUEIRO', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (46, 'CREMA«√O', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (47, 'CRUZEIRO (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (48, 'CURI”-UTINGA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (49, 'CUTIJUBA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (50, 'FAROL (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (51, 'F¡TIMA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (52, 'GUAM¡', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (53, 'ITAITEUA (OUTEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (54, 'JURUNAS', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (55, 'MANGUEIR√O', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (56, 'MANGUEIRAS (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (57, 'MARACACUERA (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (58, 'MARACAJ¡ (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (59, 'MARACANGALHA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (60, 'MARAHU (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (61, 'MARAMBAIA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (62, 'MIRAMAR', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (63, 'MURUBIRA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (64, 'NATAL DO MURUBIRA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (65, 'NAZAR…', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (66, 'PARACURI (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (67, 'PARAÕSO (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (68, 'PARQUE GUAJAR¡ (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (69, 'PARQUE VERDE', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (70, 'PEDREIRA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (71, 'PONTA GROSSA (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (72, 'PORTO ARTHUR (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (73, 'PRAIA GRANDE (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (74, 'PRATINHA (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (75, 'REDUTO', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (76, 'SACRAMENTA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (77, 'S√O BR¡S', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (78, 'S√O CLEMENTE', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (79, 'S√O FRANCISCO (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (80, 'S√O JO√O DO OUTEIRO (OUTEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (81, 'SOUZA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (82, 'SUCURIJUQUARA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (83, 'TAPAN√ (ICOARACI)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (84, 'TEL…GRAFO SEM FIO', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (85, 'TENON…', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (86, 'TERRA FIRME', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (87, 'UMARIZAL', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (88, 'UNA', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (89, 'VAL-DE-C√ES', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (90, 'VILA (MOSQUEIRO)', 170);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (91, 'AGROVILA IRACEMA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (92, 'APE⁄', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (93, 'BET¬NIA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (94, 'CAI«ARA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (95, 'CARIRI', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (96, 'CENTRO', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (97, 'CRISTO REDENTOR', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (98, 'ESTRELA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (99, 'FONTE BOA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (100, 'HELIOL¬NDIA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (101, 'IANETAMA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (102, 'IMPERADOR', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (103, 'JADERL¬NDIA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (104, 'JARDIM DAS AC¡CIAS', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (105, 'NOVA OLINDA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (106, 'NOVO ESTRELA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (107, 'PIRAPORA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (108, 'SALGADINHO', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (109, 'SANTA CATARINA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (110, 'SANTA LÕDIA', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (111, 'S√O JOS…', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (112, 'SAUDADE I', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (113, 'SAUDADE II', 187);
INSERT INTO TBL_BAIRRO (CD_BAIRRO, NM_BAIRRO, CD_CIDADE)
                VALUES (114, 'TITANL¬NDIA', 187);

COMMIT WORK;
